- src/ui/color.css.ts
- close #12 
- 기존 style 객체 값에서, globalVars 객체에 직접 접근하도록 수정했습니다. 이제 recipe 적용 될거에요. 
- color와 background 함수를 각각 나누면 코드 중복이 발생되어서, color, background 프로퍼티를 만들어서 사용할지 아니면 그냥 하나로 할지 고민해봤는데, 이미 recipe에서 배경과 색을 구분지어놔서 color로만 가도 될거 같아요~
연관된 issue: #12
> bug: color 적용안되는 문제 해결

- .github/workflows/chromatic.yml
- .github/workflows/ci.yml
- .gitignore
- eslint.config.js
- package.json
- pnpm-lock.yaml
> chore: 스토리북 배포

- src/assets/icon/name=arrow_righr.svg
- src/ui/button-text/button-text.css.ts
- src/ui/button-text/button-text.stories.tsx
- src/ui/button-text/button-text.tsx
- src/ui/button-text/index.ts
- src/ui/button/index.ts
- close #22 
- button-text 컴포넌트 
-
연관된 issue: #22
> feat: button-text 추가

- package.json
- pnpm-lock.yaml
- src/ui/dialog/dialog.css.ts
- src/ui/dialog/dialog.stories.tsx
- src/ui/dialog/dialog.tsx
- src/ui/dialog/index.ts
- close #27 
- dialog 컴포넌트 추가했습니다. 
-
연관된 issue: #27
> feat: dialog 컴포넌트 추가

- .github/workflows/typedoc.yml
- .gitignore
- eslint.config.js
> chore: typedoc 배포 workflow 추가

- src/pages/login/index.tsx
- src/pages/login/loginSection/index.tsx
- src/pages/login/loginSection/styles.css.ts
- src/pages/login/styles.css.ts
- src/ui/button-text/button-text.css.ts
- close #29 
- 로그인 페이지
- react 훅폼, zod로 유효성 검사
-
연관된 issue: #29
> feat: login 페이지 개발

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/pages/userinfo/assets/dropdown-check.tsx
- src/pages/userinfo/components/BirthStepFunnel.tsx
- src/pages/userinfo/components/GenderStepFunnel.tsx
- src/pages/userinfo/components/NameStepFunnel.tsx
- src/pages/userinfo/index.tsx
- src/pages/userinfo/page.styles.css.ts
- src/pages/userinfo/schema.ts
- src/pages/userinfo/userInfoStepState.ts
- tsconfig.app.json
- tsconfig.json
- 유저 정보 입력받는 퍼널을 추가했습니다
- 절대경로 인식하도록 tsconfig를 수정했습니다
- 중복 코드가 있긴 한데 추후 수정하거나 중복을 허용해도 될 것 같습니다
- forwardRef를 사용하지 않았다고 에러가 뜨는데 react 19로 업그레이드 하면 될 것 같습니다
- Select 컴포넌트는 디자인 수정이 있을 것 같아서 최대한 비슷하게만 만들어 놓았습니다
-
연관된 issue: #36
> feat: 유저 정보 입력 퍼널 추가

- .github/workflows/cd.yml
- .github/workflows/chromatic.yml
- .github/workflows/ci.yml
- .github/workflows/typedoc.yml
- aws s3, cloudfront에 배포하는 워크플로우를 추가했어요
-
연관된 issue: #31
> chore: aws 배포 스크립트 추가

- src/pages/home/components/recommend-category.css.ts
- src/pages/home/components/recommend-category.tsx
- src/pages/home/components/recommend-product.css.ts
- src/pages/home/components/recommend-product.tsx
- src/pages/home/index.tsx
- src/pages/home/mock-product.ts
- src/pages/home/recommend-category.ts
- src/pages/home/styles.css.ts
- src/ui/app-bar/app-bar.styles.css.ts
- src/ui/card/card.css.ts
- src/ui/card/card.tsx
- src/ui/chip/chip.styles.css.ts
- src/ui/search-field/search-field.styles.css.ts
- src/ui/spacer/spacer.css.ts
- src/ui/spacer/spacer.tsx
- src/ui/switch/switch.tsx
- 홈페이지 UI를 추가했습니다
- 캐러셀 등등 추후 수정해야할 부분은 주석으로 남겨놓았습니다.
연관된 issue: #44
> feat : 홈페이지 UI 추가

- src/hooks/useInput.ts
- src/pages/search/components/popular-keyword.css.ts
- src/pages/search/components/popular-keyword.tsx
- src/pages/search/components/recent-keyword.css.ts
- src/pages/search/components/recent-keyword.tsx
- src/pages/search/components/recommend-keyword.css.ts
- src/pages/search/components/recommend-keyword.tsx
- src/pages/search/index.tsx
- src/pages/search/result/index.tsx
- src/pages/search/result/style.css.ts
- src/pages/search/style.css.ts
- src/ui/card/card.css.ts
- src/ui/card/card.tsx
- src/ui/chip/chip.tsx
- src/ui/switch/switch.styles.css.ts
- close #50 
- 제품 검색
- AI, 제품 검색 키워드에 따라 라우터 바꾸기
- 최근 검색어: 검색 키워드 입력시 로컬스토리지에 최근검색어 저장
- chip 컴포넌트 default 부분 추가 (acitve시에만 delete 아이콘이 생김 문제 해결)
- 스위치 폰트 이슈 해결, unset 삭제
- useInput 훅 
- 재품 결과 페이지 개발 (쿼리스트링 적용)
- Card 컴포넌트 넓이 동적으로 추가
- 검색 시 입력 단어 나오는건 뺐습니다. API 필요! 
- 동환님 코드 수정(switch, chip, card)
연관된 issue: #50
> feat: 제품검색 페이지 추가

- src/pages/category/result/index.tsx
- src/pages/home/index.tsx
- src/pages/search/components/recent-keyword.tsx
- src/pages/search/components/recommend-keyword.tsx
- src/ui/chip/chip.stories.tsx
- src/ui/chip/chip.styles.css.ts
- src/ui/chip/chip.tsx
…부에서 아이콘 주입하도록 변경
- chip이 color, borderColor, typo, backgroundColor 커스텀 할수 있도록 변경
- chip 사용한 각 페이지에 적용
- storybook 변경
-
연관된 issue: #62
> fix: chip 컴포넌트 props 변경

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/pages/product/index.tsx
- src/ui/tab/index.ts
- src/ui/tab/tab-content.tsx
- src/ui/tab/tab-label.tsx
- src/ui/tab/tab.stories.tsx
- src/ui/tab/tab.styles.css.ts
- src/ui/tab/tab.tsx
- close #71 
- 
- customTabsListClass을 통해 라벨의 간격을 조정하도록 만들었습니다. 
연관된 issue: #71
> feat: tab 컴포넌트

- src/pages/home/components/recommend-product.tsx
- src/pages/home/index.tsx
- src/pages/pillbox/manage/index.tsx
- src/pages/pillbox/manage/page.css.ts
- src/pages/register/agreementBottomSheet.css.ts
- src/ui/card/horizontal-card.css.ts
- src/ui/card/horizontal-card.tsx
- src/ui/check-box/check-box.css.ts
- src/ui/check-box/check-box.tsx
- src/ui/check-box/index.ts
> feat: 내 약통 관리 페이지

- src/pages/cart/index.tsx
- src/pages/cart/page.css.ts
- src/pages/pillbox/manage/index.tsx
- src/pages/pillbox/manage/page.css.ts
- src/router.tsx
- src/ui/card/horizontal-card.tsx
- 장바구니 페이지 ui를 추가했습니다
- 링크 복사를 어떻게 할지는 백이나 기획과 논의해봐야 할 것 같습니다
-
연관된 issue: #68
> feat: 장바구니 페이지 ui 추가

- src/pages/mypage/index.tsx
- src/pages/mypage/page.css.ts
- 마이페이지 ui를 작업했습니다.
- 각 아이템을 클릭했을 시 라우팅 하는건 다른 페이지 작업이 진행 된 후에 추가할 것 같습니다 
-
연관된 issue: #74
> feat: 마이 페이지 퍼블리싱 추가

- src/apis/auth.ts
- src/apis/fetcher.ts
- src/constants/index.ts
- src/constants/storages.ts
- src/main.tsx
- src/mocks/browser.ts
- src/mocks/handlers/auth.ts
- src/pages/login/loginSection/index.tsx
- src/pages/register/components/EnterStepFunnel.tsx
- src/pages/register/components/PasswordStepFunnel.tsx
- src/pages/register/components/VerificationStepFunnel.tsx
- src/pages/register/index.tsx
- src/pages/register/registerStepState.ts
- close #75
- 인증 관련 api를 합쳤습니다
- 로그인하면 액세스 토큰 로컬스토리지에 저장하게 했어요
- 이메일 인증 api가 문제가 있어서 완벽하게 테스트는 못하고 이메일 인증 이후 부분은 msw로 테스트했습니다.
-
연관된 issue: #75
> feat: auth api 추가

- src/apis/auth.ts
- src/pages/home/components/carousel-dot-button.tsx
- src/pages/home/components/carousel.tsx
- src/pages/home/components/embla.css.ts
- src/pages/home/components/slides/category-slide.tsx
- src/pages/home/index.tsx
- src/pages/home/recommend-category.ts
- close #87 
- 홈 페이지에 캐러셀을 적용
- verify api path 오타 수정
- 
연관된 issue: #87
> feat: 홈페이지에 캐러셀 적용

- src/apis/product.ts
- src/mocks/browser.ts
- src/mocks/handlers/product.ts
- src/pages/search/result/index.tsx
- src/query/product.ts
- close #90
- 검색 api 연동했습니다
- 정렬이나 카테고리, 관련 성분은 아직 되어있지 않아서 제외했습니다
-
연관된 issue: #undefined
> feat: 검색 api 연동

- src/apis/auth.ts
- src/apis/user.ts
- src/components/LocalErrorBoundary.tsx
- src/mocks/browser.ts
- src/mocks/handlers/user.ts
- src/pages/mypage/index.tsx
- src/pages/mypage/manage/components/birth-bottom-sheet.tsx
- src/pages/mypage/manage/components/nick-name-bottom-sheet.tsx
- src/pages/mypage/manage/hooks/useBottomSheet.tsx
- src/pages/mypage/manage/index.tsx
- src/query/user.ts
- src/ui/toast/toast.tsx
- close #93
- 회원정보 조회 api 연동
- 회원정보 수정 api 연동
- 회원 탈퇴 api 연동
- 로그아웃 구현 -> accessToken 제거하는 식으로 했습니다
-
연관된 issue: #93
> feat: 회원정보 관련 api 연동

- src/pages/mypage/manage/components/birth-bottom-sheet.tsx
- src/pages/mypage/manage/components/nick-name-bottom-sheet.tsx
- src/pages/userinfo/components/BirthStepFunnel.tsx
- src/pages/userinfo/components/NameStepFunnel.tsx
- 생년월일 포맷 yyyy.mm.dd에서 yyyy-mm-dd로 수정했습니다
-
연관된 issue: #undefined
> fix: 생년월일 포맷 수정

- src/pages/pillbox/new/components/KeywordList.css.ts
- src/pages/pillbox/new/components/KeywordList.tsx
- src/pages/pillbox/new/components/PillBoxCardList.css.ts
- src/pages/pillbox/new/components/PillBoxCardList.tsx
- src/pages/pillbox/new/index.tsx
- src/pages/pillbox/new/page.css.ts
- src/ui/search-field/search-field.tsx
- close #108
- 내 약통 추가페이지 ui 및 프론트엔드 로직 추가했습니다
- 검색어 하이라이팅은 추후 api가 추가되면 연동하려고 합니다
-
연관된 issue: #108
> feat: 내 약통 추가 페이지 ui

- src/components/search-fallback.tsx
- src/mocks/handlers/user.ts
- src/pages/cart/index.tsx
- src/pages/category/index.tsx
- src/pages/home/index.tsx
- src/pages/mypage/manage/index.tsx
- src/pages/onboarding/index.tsx
- src/pages/product/index.tsx
- src/pages/search/index.tsx
- src/pages/search/result/index.tsx
- close #112
- 페이지에 진입할 때 에니메이션을 추가했습니다
-
연관된 issue: #112
> feat: 페이지 애니메이션 적용

- src/constants/category.ts
- close #116 
- 카테고리 - 관련성분 매핑 상수 값을 수정했습니다
-
연관된 issue: #116
> fix: 카테고리, 관련성분 매핑 상수 수정

- .gitignore
- eslint.config.js
- src/pages/home/index.tsx
- src/pages/home/recommend-category.ts
- 홈화면 캐러셀의 카테고리 아이템가 하나씩 밀려있던 문제를 수정했습니다
-
연관된 issue: #126
> fix: 홈 카테고리 아이템 수정

- src/apis/mutation/myMedicine.ts
- src/apis/query/myMedicine.ts
- src/apis/types/myMedicine.ts
- src/pages/pillbox/manage/index.tsx
- src/pages/product/index.tsx
- src/ui/card/horizontal-card.tsx
- 내 약통 페이지에서 삭제 api 연동했습니다
-
연관된 issue: #123
> feat: 내 약통 삭제 api 연동

- src/apis/mutation/cart.ts
- src/apis/query/cart.ts
- src/apis/types/cart.ts
- src/pages/cart/components/Fallback.tsx
- src/pages/cart/components/fallback.css.ts
- src/pages/cart/index.tsx
- src/pages/cart/page.css.ts
- src/pages/pillbox/manage/index.tsx
- src/pages/pillbox/new/components/PillBoxCardList.tsx
- src/pages/product/index.tsx
- 장바구니 관련 api 연동
- queryClient.invalidateQueries를 사용했을때 query를 이용해서 state를 만든 컴포넌트에서 리렌더링이 되지 않아 상태변경이 반영되지 않는 문제가 있었어요. 이를 queryClient.resetQueries를 이용해 해결했습니다
-
연관된 issue: #124
> feat: 장바구니 관련 api 연동

- src/pages/home/index.tsx
- src/pages/home/styles.css.ts
- src/ui/bottom-navigation/bottom-navigation.tsx
> fix: 개발 안된 부분 주석처리

- src/apis/fetcher.ts
> fix: baseurl 수정

- src/pages/mypage/index.tsx
- 마이페이지에서 미구현된 부분 가렸습니다.
-
연관된 issue: #141
> fix: 마이페이지 안된 부분 가리기

- src/pages/cart/index.tsx
- 장바구니 전체 선택 해제 시 Fallback으로 가는 오류 수정
-
연관된 issue: #138
> fix: 장바구니 전체 선택 해제 시 Fallback으로 가는 오류 수정

- src/pages/search/components/recent-keyword.tsx
- src/pages/search/index.tsx
- close #137 
-
-
연관된 issue: #137
> fix: 개별삭제, 클릭 시 검색 이동

- src/pages/product/index.tsx
> fix: 상세 페이지 건강고민 카테고리, 관련성분 일정 개수 이하로 출력되도록 수정

- src/pages/pillbox/index.tsx
- src/pages/pillbox/page.css.ts
- close #148 
-
-
연관된 issue: #148
> feat: 내약통 페이지 약 ui 추가

- src/components/PrivateRoute.tsx
- src/components/cart-botton.tsx
- src/pages/login/index.tsx
- src/pages/product/index.tsx
- src/router.tsx
- src/ui/bottom-navigation/bottom-navigation.stories.tsx
- src/ui/bottom-navigation/bottom-navigation.tsx
- src/ui/dialog/dialog.tsx
- src/ui/layout/bottom-navigation-layout.tsx
- src/ui/layout/mobile-layout.stories.tsx
- src/utils/isLogin.ts
- 로그인 여부에 따라 바텀 내비게이션이나 카트 클릭시 다이얼로그 띄우도록 설정
- 로그인 안했는데 url로 접근시 로그인 페이지로 리다이렉트
- 로그인 페이지 뒤로가기 안되는 문제 수정
-
연관된 issue: #149
> feat: 로그인에 따라 페이지 접근 허용 설정

- src/apis/query/myMedicine.ts
- src/apis/query/product.ts
- src/apis/types/myMedicine.ts
- src/apis/types/product.ts
- src/pages/pillbox/index.tsx
- src/pages/product/components/analysis-section.tsx
- src/pages/product/index.tsx
> fix: 성분분석관련 api 추가

- src/pages/home/index.tsx
- close #154 
- 왜 안되나 했는데 텍스트를 잘 못썼네요..ㅜㅜㅜ
-
연관된 issue: #154
> fix: 홈 화면에서 증상 AI 검색 누를때 제품검색 토글되는 버그 수정

- src/apis/query/product.ts
- src/apis/types/product.ts
- src/pages/search/components/ai-search-section.tsx
- src/pages/search/result/index.tsx
- src/pages/search/result/style.css.ts
> feat: ai 검색 UI 추가, api 연동

- src/pages/search/components/popular-keyword.css.ts
- src/pages/search/components/popular-keyword.tsx
- src/pages/search/components/recommend-keyword.tsx
- src/pages/search/index.tsx
- close #152 
-
-
연관된 issue: #152
> bug: 추천 검색, 인기 검색 키워드 클릭 시 결과 페이지로 넘어가게 추가

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/components/ClarityEffector.tsx
> chore: 모니터링 도구 추가

- src/App.tsx
> fix: 앱 심사를 위해 모니터링 도구 주석 처리

- src/pages/cart/index.tsx
- src/pages/mypage/manage/components/birth-bottom-sheet.tsx
- src/pages/mypage/manage/components/nick-name-bottom-sheet.tsx
- src/pages/mypage/manage/index.tsx
- src/pages/pillbox/manage/index.tsx
- src/pages/pillbox/new/components/PillBoxCardList.tsx
- src/pages/product/index.tsx
- vite.config.ts
- api 요청 실패시 토스트를 띄우도록 했습니다
-
연관된 issue: #170
> feat: 요청 실패시 토스트 추가
